<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Affiliate for Magento 2
*/
?>
<?php
/** @var \Amasty\Affiliate\Block\Account\Refer $block */
?>

<?php if ($block->showLinks()): ?>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script
        type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $block->escapeHtml($block->getProfileId()) ?>">
    </script>
    <div class="addthis_inline_share_toolbox affiliate_social_buttons"></div>
    <script type="text/javascript">
        var addthis_share = {
            url_transforms: {
                add: {
                    referring_service: '{{code}}',
                    <?php echo $block->getUrlAccountParameter() ?>: '<?php echo $block->getReferringCode() ?>'
                }
            }
        }
    </script>
<?php endif; ?>
