<?php
/** @var \Amasty\Reports\Block\Adminhtml\Report\Customers\Abandoned\Information $block */
?>
<p class="advertising">
    <?php if (!$block->isAcartEnabled()): ?>
        <?= $block->escapeHtml(__(
            'Send catchy reminders to your customers using <a href="%1" target="_blank">Abandoned Cart Email extension</a> extension.',
            $block->escapeUrl($block->getAcartUrl())
        ), ['a']) ?>
    <?php endif; ?>
    <?php if (!$block->isRequestQuoteEnabled()): ?>
        <?= $block->escapeHtml(
            __(
                'Create personal offer with <a href="%1" target="_blank">Custom Quote extension</a>.',
                $block->escapeUrl($block->getRequestQuoteUrl())
            ),
            ['a']
        ) ?>
    <?php endif; ?>
</p>
