<div class="slider-revolution-update-list">

	<h3 class="version-number">Version 6.2.15.5 (9th December 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">New Features</strong></div>
	<ul>
		<li>Added ThemePunch update servers and Vimeo frame to the Content Security Policies whitelist</li>
	</ul>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
	<ul>
		<li>Removed unapplicable show double jQuery error function</li>
	</ul>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Fixed error in drag and drop media upload</li>
        <li>Fixed problem with link actions urls</li>
		<li>Fixed missing Add-On admin minified scripts issue</li>
		<li>Fixed admin user dropdown and slider overvew navigation overlay issue</li>
		<li>Fixed issue with missing images after importing the slider</li>
		<li>Fixed bug in editing Story Block package templates sliders</li>
		<li>Fixed the Whiteboard Add-On update popup problem</li>
		<li>Corrected the scope of delete_all_slides method</li>
		<li>Fixed bug in image optimizer</li>
		<li>Fixed error when the slider image is missing</li>
		<li>Fixed text layers localization</li>
		<li>Fixed the admin slider preview bug caused by the failed script tag injection into the json encoded html response</li>
		<li>Fixed loading of the minified Vimeo player script for Magento versons below 2.3.5</li>
		<li>Fixed the object library resizing issue</li>
    </ul>

	<h3 class="version-number">Version 6.2.15.4 (26th October 2020)</h3>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
	<ul>
		<li>Removed unapplicable JS to footer feature</li>
	</ul>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Fixed problem with slide links behind layers</li>
		<li>Fixed insert image from the Object Library bug</li>
		<li>Fixed undefined variable error on animations update</li>
		<li>Fixed Magento 2.4.1 image uploader problem</li>
		<li>Fixed the possible undefined jQuery error on the frontend</li>
		<li>Fixed problem with resolving images urls from another domain</li>
		<li>Fixed error on slider import</li>
    </ul>

	<h3 class="version-number">Version 6.2.15.3 (14th August 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">New Features</strong></div>
	<ul>
		<li>Added external sources to the whitelist of Content Security Policies</li>
	</ul>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
	<ul>
		<li>Added more sizes to the optmize slider images feature</li>
	</ul>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Fixed issue with getting image file name on the frontend (undefined path error)</li>
        <li>Fixed issue with redirects when generating slider preview in the backend</li>
		<li>Fixed error in the overview page when frontend preview preload url is not available</li>
		<li>Fixed export to HTML feature</li>
    </ul>

	<h3 class="version-number">Version 6.2.15.2 (6th August 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Fixed missing quote in add_inline_double_jquery_error</li>
        <li>Fixed PHP 7.4 compatibility issues</li>
    </ul>

	<h3 class="version-number">Version 6.2.15.1 (24th July 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Added missing gallery images helper to Magento 2.1.x patch</li>
        <li>Fixed get_attachment_image_src error on frontend</li>
    </ul>

	<h3 class="version-number">Version 6.2.15 (20th July 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">New Features</strong></div>
	<ul>
		<li>Added the layer upscaling option module wide for fullwidth sliders which will open new design directions for % scaled elements i.e (See our Charity Map Template functionality)</li>
		<li>Added align by option for the progress bar which can now be aligned by grid and module</li>
		<li>Added further warnings in editor in case of a conflict with themes/plugins and server accessability</li>
		<li>Added an option to ignore mobile browser height changes based on scrolls. The urlbar and toolbar do disappear based on scroll, which would resize the fullscreen sliders. Set per module if you wish to ignore these behaviour of the mobile browser. This option is enabled by default</li>
		<li>Introducing new options for the progress bar:
			<ul>
				<li>Modes: Show progress of full slider module or show progress of single slide</li>
				<li>Progress types: horizontal, vertical, CW circle, CCW circle</li>
				<li>Progress directions: RTL and LTR mode</li>
				<li>Styling: background, color, gap size and color</li>
				<li>Visibility on desktop, notebook, mobile and tablet</li>
			</ul>
		</li>
		<li>Introducing a core listener system which will synchronise and manage sliders on pages automatically</li>
		<li>Layer background supports now also image sources from stream</li>
		<li>Added custom fonts list to global settings, which supports custom fonts in the editor area also.<br>Available options: font family name, url to font style, available font weights, load font in front- and/or backend environment</li>
		<li>Added Image Background from Stream for Layers</li>
		<li>Added color skins to define global colors for different color attributes through any kind of element. I.e. create a color group for highlight colors and then attach them to the font-color, border-color, navigation elements, slide backgrounds, shape colors and so on. This is the best way to edit templates very quick and simple.</li>
		<li>Carousel offset values can scale now also linear to slide scales to allow different horizontal carousel animations based on scale, horizontal offset and this new option</li>
		<li>Added retina canvas support for the Paintbrush AddOn. The Paintbrush AddOn version 2.1.3 is required</li>
		<li>Carousel slides will load on demand with lazy loading if lazy loading is set to single/smart. The amount of loaded elements depend on the amount of visible slides set in the carousel settings.</li>
		<li>Added auto width slides for the carousel mode (justified) Option.</li>
		<li>Added sticky mode for the carousel layout</li>
		<li>Added permanent visible individual layers, to extend the "visible all" layers feature in the carousel mode. This gives you more freedom as for which layers should always be visible and which should only be visible on slide focus</li>
		<li>Added an force overflow hidden option for the carousel mode which can be very useful in the new justified carousel mode</li>
		<li>Added new option to hide hover functionality on layers if the Slider is loaded on mobile.</li>
		<li>Added Page Template "Slider Revolution Blank Page" for Posts too</li>
		<li>Added Background Color Page option for Slider Revolution Blank Page Template</li>
		<li>Added Block Settings (PopUp, Spacing, zIndex etc) for Gutenberg, WP Bakery Page Builder and Elementor</li>
		<li>Moving layers in animation mode will move the layers x/y transform value in the selected frame. This will allow to fine tune the animation positions of layers</li>
		<li>Drag and drop images and or videos to the editor to create layers on demand to shorten the required steps to create image/video layers</li>
		<li>German and French translation added</li>
		<li>Added a link help option to slide and action links, to help auto selection of http and https protocols for links</li>
		<li>Added a file and media optimizer feature, available on pages/posts, overview and Slider Editor mode to optimize embeded media files and to get a general overview about loaded filesizes</li>
		<li>Added guide lines based on grid and on similar aligned layers where layers can snap to these guidlines also. Even gaps can be set to snap by predefined spaces</li>
		<li>Added new depth on the overview page for slides in sliders
			<ul>
				<li>Rename, delete, publish and unpublish slides straight in the overview without opening the editor itself</li>
				<li>Change sorting, set admin thumbnail and open the editor with selected slide straight from the overview</li>
			</ul>
		</li>
		<li>Added custom font-family definition in global settings to extend the text layer font-family selectors</li>
		<li>Added high contrast mode for better readability. Turn this option on/off in the global settings</li>
		<li>Added admin thumb image to the Slider Revolution Gutenberg Block</li>
		<li>Added a new text stroke option in the advanced styles</li>
	</ul>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
	<ul>
		<li>Slicey AddOn's "Min PanZoom" value can be now also changed anything to >=100 (version 2.0.2 required)</li>
		<li>Synchronised the video animation start with the slide change to start videos earlier</li>
		<li>Updated many core functions to reduce loading times</li>
		<li>Reduced the slider preparation times</li>
		<li>Massively reduced CPU and GPU usage during slider processes</li>
		<li>Favorit selection on templates in packages will show now in the favorite list as well</li>
		<li>Links with target="_blank" will be extended with the rel="noopener" attribute to avoid performance and security issues</li>
		<li>Double defined slide link actions : "Next Slide" and "Previous Slide" removed from the "Jump To Slide" action to avoid misunderstanding (existing values are still available)</li>
		<li>Added ScrollTo GreenSock Plugin with the latest Version to avoid issues where 3th Party Plugins and Themes using RS Libraries with older components of GreenSock</li>
		<li>ThemePunch tool main reference "punchgs" has been replaced by "tpGS"</li>
		<li><b>GreenSock</b> Engine update from Version 2.x to <b>Version 3.x</b></li>
		<li>Easing now have new aliases. i.e. Power2.easeInOut now can be referenced with short names like power2.inOut</li>
		<li>Added carousel mobile swipe and desktop mobile swipe options under the navigation touch section which allows you to disable the carousel navigation via touch if needed</li>
		<li>Timeline limit extended to a maximum of 3:00 min</li>
		<li>Merged the AddOn notices into one single notice</li>
		<li>Optimized page loading</li>
		<li>Reduced file sizes for faster loading times</li>
		<li>Added sharp corners also to shape layers</li>
		<li>Updated google fonts</li>
		<li>Updated the preview function to show a more realistic preview in the backend using desktop mode</li>
		<li>Updated the carousel engine for a better performance and smoother animations</li>
		<li>Added throw phyiscs to the carousel engine</li>
		<li>Added a workaround for a Safari bug where image layer animations shift when the opacity is below 1 at start</li>
		<li>Essential Grid will now be parsed in layer. On start animation, Essential Grid will call the redraw option</li>
		<li>Static layer editor will now honor the last edited slide and will resize and reposition none editable elements for better orientation in the static slide editing</li>
		<li>Warning added on background filters to inform about incompatible filters on videos for the Edge and Internet Explorer Browsers</li>
		<li>Videos in the editor can now have "auto" height and "%" width independent if they are positioned in columns, groups or on the stage directly</li>
		<li>The gutenberg block opens the module library now directly when added</li>
		<li>Updated google font list</li>
		<li>Removed unneeded font stylings from img layers</li>
		<li>The slide links and layer action links http/https auto adjustment behavior can now be changed as an own option</li>
		<li>Optimized the output to ignore the font style based settings on unrelated layers</li>
		<li>Updated some output details if something goes wrong for better understanding</li>
		<li>Optimized the snap and guideline settings to simplify the usage. If it is enabled, it will always show guidelines and will always snap to them.</li>
		<li>Changed the values for carousel opacity, rotation and scale. some of the values were not working properly, some of the values were the other way around.</li>
		<li>Folders in overview will show now the first found elements admin thumb even in multiple depths</li>
		<li>GreenSock TweenMax library updated to version 2.1.3.</li>
		<li>Changed the Event Manager meta for layers from {{event_event_id}} to {{event_id}}</li>
		<li>Added an option in the Panorama AddOn to lock vertical draggings. Panorama AddOn 2.1.0 is required</li>
		<li>Change Facebook API connection to access tokens (because of the new API security guidelines)</li>
		<li>Changed the usage of wp_upload_dir() in the object library, so that the calls of it are minimized, as it caused issues on Pantheon Servers</li>
		<li>Changed behavior of certain functions to better support Pantheon servers</li>
		<li>Modal loading will now use the cover background already before the modal window is loaded. This happens only if the cover background is enabled and a color is selected</li>
		<li>Importing template packages that has a modal slider, will now set all the needed actions in the layers so that the modal works directly. Please note that for already downloaded sliders, a new installation is needed with the "Re-Download Online" option set to "on"</li>
		<li>Changes due to Instagram API retiring public information for security reasons:
			<ul>
				<li>Removed "likes" meta. The output of former used "likes" meta will be blank</li>
				<li>"author name" meta will now display the searched user name</li>
			</ul>
		</li>
		<li>Default cycles for scale animation updated to (0.5 to 1) from (-50 to 50)</li>
        <li>Removed update now button from overview page</li>
		<li>Removed not applicable troubleshooting options</li>
	</ul>
	<div class="bugfix"><strong style="font-weight:700">Bugfixes</strong></div>
	<ul>
		<li>Position information will be hidden by dragging elements within columns or out of the columns to hide unneeded undefined parameters</li>
		<li>Added protection against infinity loops in the overview page in case folders were somehow pointing into each other creating recursive traps</li>
		<li>Fixed a bug where text and button layers with placholders did not refresh the visibility after editing their real content in the editor</li>
		<li>Fixed a bug where video streams would not work properly</li>
		<li>Fixed Instagram Stream functionality</li>
		<li>Fixed a bug where JavaScript based simple links doubles the output and brakes the link process. This was an earlier fix for the action "CallBack" where ":" chars did brake the callback function. Both bugs are fixed now</li>
		<li>Fixed issue with ":" special chars in call back actions</li>
		<li>Fixed an issue where opening a modal with slide "x" multiple times was breaking the opening process</li>
		<li>Fixed an odd zIndex issue where not focused slides in the editor with more layers than current editing slide may loose their zindex on layers after saving the full module</li>
		<li>TypeWriter AddOn fixes version 2.0.3:<ul>
			<li>Added support for inline style on span tags</li>
			<li>Added option to change the cursor color</li>
		</ul></li>
		<li>Fixed a bug where action triggered loop animations did not start the animation. Also fixed loop animated elements which jumped to loop animation frame 0 during the slide out animation</li>
		<li>Fixed issues with row/column heights where images that were added with padding into the first column, and the height of the image may negatively influence the calculation of the module height on slide swap</li>
		<li>Fixed horizontal and vertical slide transition issues</li>
		<li>Fixed a bug that leads to broken post based sliders</li>
		<li>Video poster will show up if video has not started and the video has been resetted (just like coming from another slide) even if "Show Poster on Pause" is not selected</li>
		<li>Video timeline now can be dragged even if "Show Poster on Pause" is selected, which is showing up with delay in this case if needed</li>
		<li>Video click will now honor original clicks and start/play videos correctly</li>
		<li>Fixed HTML5 video fullscreen playback on IE11</li>
		<li>Fixed JavasScript error if an Essential Grid exists on the page and the Slider tries to recall Essential Grid's refreshing method</li>
		<li>Fixed an issue where the loading of modules with ajax, removing them (with or without revkill method) and readding them to a later point in time did not start the modules correctly</li>
		<li>Fixed an issue where the alt for slide images was not written if it was empty</li>
		<li>Fixed an issue where AddOn downloads showed up as success and after reload the AddOn is not installed</li>
		<li>Fixed an issue not displaying photos from a Facebook albums</li>
		<li>Fixed a bug where static layers with Custom animations may do not appear in certain situations</li>
		<li>Panorama Addon 2.1.2: Added support for external images</li>
		<li>Fixed an issue with a tag links not being able to be clicked in carousels in some cases</li>
		<li>Fixed undefined JavaScript error in the thumbnail position calculation in case thumbnails were loaded with delay on stage</li>
		<li>Fixed JavaScript error if the progressbar stopped due to a mouse event before the progressbar has been created. This issue occured in very rare situations only</li>
		<li>Fixed a lazy loading issue where relative paths created by 3rd party plugins could not be compared with loaded filepaths in some very odd cases</li>
		<li>Fixed mobile fallback on background images issue</li>
		<li>Before After 2.0.7: Fixed a bug where the divider drop shadow wasn't getting a correct color</li>
		<li>PaintBrush 2.1.8: Optimized rendering for FireFox</li>
		<li>Particles Effects 2.2.3: Reduced the sensitivity of the particle reduction calculation</li>
		<li>Particles Effects 2.2.3: Are now slowly removed over period of 5 seconds instead of removing them suddenly</li>
		<lI>Fixed an issue where toggled layers become visible and may overlay hoverable areas on underlaying modules before they started at all</lI>
		<li>Media dimension calculation in rows, columns and groups was not always set on the first rendering. If the dimension of the parent container change, childen will reflow to show all layer sizes in the correct dimension</li>
		<li>Removing a slide during slider process broke the progress. Issue is fixed now</li>
		<li>Added perspective during layer animations to avoid unsmooth scaling, jittering effects</li>
		<li>Fullscreen slider offset heights will be calculated on the very early start to avoid small height jumps</li>
		<li>Calculating parent container dimensions for layer frame animations with top, left, right, bottom sources will now respect groups, rows and columns which will also fix the predefined Layer Library animation effects</li>
		<li>New progress bars vertical and horizontal could not run on IE Edge and IE11 due the quick rendering process which detached and reattached elements to DOM</li>
		<li>Removed overflow:hidden for IE browsers if the slider should go to fullwidth without the support of the sourrounding environment. This will now force in IE11 and Edge the containers to show the real fullwidth again</li>
		<li>Before After 2.0.6: Fixed an issue where the Before After Slider did not resize well in modal after the modal opened a 2nd time in the browser</li>
		<li>Fixed console errors in case static layers did not exist in some very rare cases</li>
		<li>Fixed the block vertical scroll option on iOS which in some cases still allowed vertical scroll after swiping horizontally</li>
		<li>Fixed a bug where block vertical scroll disabled the click on a tags and link actions</li>
		<li>Carousel swipe on iOS was not possible if the slide link existed on single slides</li>
		<li>Removed unneeded console logs</li>
		<li>Fine tuned the file optimizer to ignore empty or not existing URLs</li>
		<li>Added iOS 9.3.5 support for parallax events</li>
		<li>Some URL parameter broke the slider on load. This issue has been fixed now</li>
		<li>Fixed video animations start on 1st loop if videos were added as layers on carousel slides</li>
		<li>ViewPort with % selection and scroll based animation may fail when the process falls back to JavaScript based calculation instead of the CSS solution. This bug has been fixed now.</li>
		<li>Fixed an annoying bug with scroll issues in the backend, where sometimes right toolbar got stuck after selecting layers, changing background types etc.</li>
		<li>Conflicts between themes and the Slider Revolution Plugin based on the GSAP library has been resolved</li>
		<li>Hover on elements were not working well in some situations if the mouse pointer was already hovering an element during the in animation.</li>
		<li>Particle Effects 2.2.1: Grab mouse interactivity failed with an JavaScript error</li>
		<li>FilmStrip 2.0.3: Fixed a bug where the filmstrip animation was getting slower after a while.</li>
		<li>FilmStrip 2.0.3: Already animating elements were still animating in the background due to a syntax error. This has been fixed now</li>
		<li>Fullwidth carousels get cut off in some cases in themes and templates. Added a new calculation way to force fullwdith carousel sliders to overflow parent containers if needed</li>
		<li>Added protection against double start of sliders during the initialisation process where in some very rare cases the process could break</li>
		<li>Added a protection against double generated IDs for different auto created slide link layers</li>
		<li>JavaScript error due to typo failure in middle arranged rows fixed</li>
		<li>Imported or updated layer actions may fail if Toggle N/M is selected. The current fix will update the values and let you resave the slider with the correct values</li>
		<li>Added new version for Tools to force Cached files to reload. In some cases Cache would not be rewritten after the plugin update</li>
		<li>OnScroll - the timeline based scroll range selection will not be shown anymore if it is not selected</li>
		<li>Fixed a bug if justify carousel was selected in combination with auto width mode, where the calculation of window width returns NaN</li>
		<li>Fixed an issue with scroll below and scroll to actions</li>
		<li>SFX box out animation makes layers already visible before "IN" animations. This issue has been fixed now</li>
		<li>Navigation thumbnails may not appear from streams in some odd cased. Issue is fixed now</li>
		<li>Fixed layer positioning issues on first load when the outer navigation container was added to auto sized sliders</li>
		<li>Added fallback to older scroll animation methods in case the template or theme is not supporting new methods</li>
		<li>Fixed varousel bg videos which will now fill (cover) the slide to make sure that no black gaps exist, if a video was added as a background video</li>
		<li>Particle Effects 2.2.0: Optimized drawing and calculations to improve performance</li>
		<li>Particle Effects 2.2.0: Added support to play/pause drawing when slider is not in viewport</li>
		<li>Particle Effects 2.2.0: Added support to measure performance and reduce number of particles to improve perfomance</li>
		<li>Added a protection against mixed urls like www.domain.com/ and domain.com/ where sometimes images could not be loaded well</li>
		<li>Fixed an issue where the Gutenberg Block ID of Slider Revolution could not be rewritten after reload</li>
		<li>Fixed a bug where the saved color schemes were not imported properly</li>
		<li>Fixed an deprecated notice in output.class.php for PHP 7.4 and newer</li>
		<li>Fixed an E_ERROR in revslider-admin.class.php</li>
		<li>Start with "predefiend" slide was not respected. Now it can be set even if the shuffle mode activated</li>
		<li>Fixed the PanZoom blur filter effect in backend, which was only rendered in the editor during the PanZoom Animation</li>
		<li>Background videos were not playing in carousel mode if the slide switched by navigation or automatically by progress. This issue is fixed now for all kind of sliders</li>
		<li>Animating Before/After AddOn split position was not available on click since core version 6.2.x. To fix the issue please update the Before/After AddOn to version 2.0.4</li>
		<li>Fixed JavaScript errors by removing loop animated layers from stage via action</li>
		<li>Fixed an issue where some pseudo elements like placeholder within inputs had a wrong line height in Safari browsers</li>
		<li>Fixed 'Slide to Left/Right/Top/Bottom' animations, which were disappearing in some cases after the second loop</li>
		<li>Fixed click events on buttons and links in mobile browsers if the swipe action with block scroll was enabled</li>
		<li>Fixed some Logic failure in Paint Brush AddOn which strongly influenced the Performance of slider processes. Requires Paint Brush AddOn version 2.1.6</li>
		<li>Images from V5 with auto width and height on root will auto get their original dimension to properly resize on smaller devices. Bug fix for sliders which have been created in older V5 SR.</li>
		<li>Fixed Lazy Load Support for Slicey AddOn. Requires Slicey 2.1.3</li>
		<li>Fixed a bug where the disabling of "Lazy Loading of Images" may break the distortion effects in some situations. Requires 2.0.1 of Distortion AddOn</li>
		<li>Fixed custom background gradient colors with easing effect where loading custom saved values stopped with JavaScript failures</li>
		<li>Fixed Firefox 3D rotation issues where clickable elements were not available due to high tilts. There is now a max tilt of 25 in Firefox for 3D parallax worlds to solve this</li>
		<li>Paint Brush 2.1.6 fix - Optimized performance</li>
		<li>Paint Brush 2.1.6 fix - Option for blur effect on brush is respected now</li>
		<li>Distortion 2.0.2 fix - Fixed a bug that caused additional calculations</li>
		<li>Distortion 2.0.2 fix - Updated canvas size implementation to improve performance</li>
		<li>Distortion 2.0.2 fix - Fixed a mousemove glitch and improved performance</li>
		<li>Distortion 2.0.3 fix - Cross origin issue</li>
		<li>Distortion 2.0.3 fix - Wrong distortion map before redrawing</li>
		<li>Bubble Morph 2.1.1 fix - Fixed bug preventing some bubblemorphs from starting</li>
		<li>Bubble Morph 2.1.1 fix - Optimized performance if page includes multiple bubblemorphs</li>
		<li>Before After Slider 2.0.5 - Fixed jQuery error if Slider loaded in Modal Sliders with Before After Addon</li>
		<li>Slicey 2.0.5 - Fixed Javascript error on Slicey Addon when Blur Filter get activated</li>
		<li>Fixed the navigation position calculation where vertical positions were not always calculated correctly</li>
		<li>Fixed miscalculation of paddings, margins and navigations in carousel mode if the padding and/or margin was set via module and carousel</li>
		<li>Fixed an error where SVG file paths for static layers in existing templates and exports may point to the wrong direction after reimporting them</li>
		<li>Old templates with YouTube or Vimeo streams did not import correctly. This bug is fixed now</li>
		<li>Fixed an bug where fonticons where not loaded in modal sliders</li>
		<li>Global Skin Colors were not working after import oder import/export of layers due wrong id references</li>
		<li>Fixed Allow FullScreen button in video settings. It will disable fullscreen options in almost all cases except HTML5 videos in Firefox and Safari which are not supported out of box unfortunately</li>
		<li>Fixed an issue where layers were not available for pointer events if they were included in other layers with scroll based animation and scroll is not yet triggered.</li>
		<li>Fixed HTML5 Video Loop and Start issues in Safari browser.  The Video will be shorten with 0.075sec and auto rewinded in case the loop option is selected to work around the native videoplayer delay bug in Safari Browser</li>
		<li>Fixed Windows Browser behaving when the modal opens to avoid small jumps and/or double scrollbars</li>
		<li>Fixed an issue where sliders could not be lunched on iOS 9.x deviced due to a JavaScript issue</li>
		<li>Corrected the naming of some attributes in the 3D parallax settings for better understanding</li>
		<li>Fixed a bug where the update process from V5.x to 6.2.1 would break in some cases the slide animation settings</li>
		<li>Fixed "first slide" and "last slide" links due the "jump to slide" action</li>
		<li>Fixed skew transforms in frontend rendering where elements kept their calculated "scale and skew" values in case any of the skew attributes had negative values</li>
		<li>Fixed layer size calculation in frontend rendering if the layer was added to a group with % based width and/or heights</li>
		<li>Fixed Thumbail and Tab positions calculation glitches if RTL navigation is enabled. </li>
		<li>Text decoration style will no longer be applied to row, column and group layers</li>
		<li>Auto width full height image layers will now respect also the image width in FireFox</li>
		<li>Importing a package into a folder will no longer return an moving error even thought the slider was properly moved</li>
		<li>Releasing Mouse outside of Modal windows will not any more close the Modal windows, to support copy/paste within text editors</li>
		<li>Fixed an issue where the touch/swipe functionality on full slide links in carousel mode was not working properly.</li>
		<li>Fixed the color animation if the text color has been animated from a different value to the default and the splitted text option was set in character, word or lines mode.</li>
		<li>Fixed hover animation issues in editor mode where the default filters added an odd black flash effect to the animation start</li>
		<li>Fixed navigation not working anymore after loading a slider in a modal that has the "Put JS To Body" option set to on</li>
		<li>Fixed a bug where old carousel sliders do not show all slides even if they should</li>
		<li>Elements without 3d animation settings will now ignore the transform perspective attribute to render layers on retina displays as sharp as possible</li>
		<li>Fixed an issue where the navigation arrows lost their thumbnail images after the first slide</li>
		<li>Fixed an issue where the navigation thumbs of a post based slider would be scaled two times</li>
		<li>Issue with Ken Burns effect in Firefox's latest browser hes been fixed where the animation stop playing after slide in transform</li>
		<li>Fixed a very rare bug where JavaScript errors blocked any further functionality in the overview page when a template has been directly installed after updating the AddOns</li>
		<li>Fixed small glitches in overview page and in editor</li>
		<li>Scroll navigation in carousel sliders has beed fixed</li>
		<li>Long Touch and swipe function in Carousel Sliders may made the whole slider container to jump and laggy</li>
		<li>Fixed an issue where moving sliders from folders to root and back broke with JavaScript error</li>
		<li>Fixed google font preload not working properly with italic fonts</li>
		<li>Fixed CountDown AddOn where the count down layers were not auto updated within groups, rows and columns. CountDown AddOn version 2.1.1 is required</li>
		<li>Carousel animation was laggy if all layers were visible on all slide elements</li>
		<li>Carousel did not auto transform to next slide and did not reacted to navigation evens if "snap to X aligment" option was turned off</li>
		<li>Carousel Elements sometimes disappearing by Swipe if max amount of elements size smaller then Document width</li>
		<li>Fixed exploding layers issues in the editor where a layer can not be moved around in the animation mode. AddOn version 2.1.0 required</li>
		<li>Fixed an issue with exploding layers where the animation on Layers with a tag will not animate smoothly. AddOn version 2.1.0 required</li>
		<li>Fixed an issue in the core of the Distortion AddOn which was breaking the slider editor in some rare cases</li>
		<li>Fixed BubbleMorph shadow options. AddOn version 2.1.0 of the BubbleMorph AddOn is required</li>
		<li>Navigation tabs and thumbs vertical scrolling will not scroll the page any more on mobile devices</li>
		<li>Fixed Avada Slider Revolution Block (bug came with the 6.1.7 update of RevSlider)</li>
		<li>Importing a package into a folder will no longer return an moving error even thought the slider were properly moved</li>
		<li>Buttons become unresponsive on mobile (both iOS and Android) if Block Scroll option is turned on</li>
		<li>Fixed Android Scroll issues on Slider when Swipe was enabled</li>
		<li>Fixed tabindex not beeing properly added</li>
		<li>Fixed a bug with the plugin_locale filter</li>
		<li>Fixed an issue with flickr not displaying images if original size is not available anymore</li>
		<li>Fixed a bug where the usage of {{featured_image_url_*}} parameters for post based and Instagram sliders did not work properly</li>
		<li>Fixed a bug where layers from the layer library could not be imported</li>
		<li>Fixed a bug where the a slide would be visible on mobile even if the setting was set that it should not be visible</li>
		<li>Fixed a bug where updating from an old version of Slider Revolution could change the animations in rare cases, so that the slider editor can not be loaded</li>
		<li>Fixed tons of small glitches in the carousel rendering. Fixed swipe failures and missing elements on the left/right side. Fixed rotation and scale issues if the varying option was set to true</li>
		<li>The slider editor will now also save published/unpublished slides even if no other setting was changed on those slides</li>
		<li>Fixed scroll effects on mobile devices</li>
		<li>The dropzone will now only be shown to real dragged files in the editor</li>
		<li>Fixed minHeight issue on fullwidth sliders. From now on it will ignore unused values set by auto layout</li>
		<li>The Toggle state of playing/pausing a slider will not jump anymore between forward and backward when the slide is changing.</li>
		<li>Fixed box-shadow issue in FireFox by removing the filter rest blur(0px) on some elements</li>
		<li>Fixed a bug where Vimeo Autoplay on iOS was not working well on the 2nd and further Loops</li>
		<li>Bubble Morph bug fixed where linear resized small containers used to shake on mobile devices. Bubble Morph 2.0.3 is required</li>
		<li>Fixed a bug where an empty Slider Revolution block opens the template library on page/post editor loading</li>
		<li>Fixed the smart loading feature, which will now load the previous/next slide content when the slide is focused</li>
		<li>Fixed a bug where the optimizer stopped working in the page editor in case the module included any AddOns</li>
		<li>Fixed inline style issues on layers when the slide link was added at the end of the slide container</li>
		<li>Fixed a bug where looped media could not be saved. After 1 reload and resave the video lost its looped state</li>
		<li>Fixed a bug where inline styled colors in splitted text (chars, lines, words) were not respected</li>
		<li>TypWriter multiple line editing bug fixed. TypeWriter version 2.0.2 required</li>
		<li>Fixed device pixel ratio issue on retina displays. The Paintbrush AddOn version 2.1.3 is required</li>
		<li>Fixed an issue where none of the YouTube playlist listitems was selected after the playlist updates</li>
		<li>Fixed click mouseenter and mouseleave actions on layers in combination with navigation show/hide, slider focus/blur events</li>
		<li>Before After AddOn split initialisation will respect all screensizes now, instead of jumping 50% on smaller screens. The Before After AddOn 2.0.3 is required</li>
		<li>Fixed Slicey AddOn compatibility with the Type Writer AddOn. Slicey 2.0.1 AddOn required</li>
		<li>Fixed Google Font loading issue if the global option for preload was selected</li>
		<li>Fixed scrollbar issues in the editor and overview pages</li>
		<li>Fixed an issue with line heights in some rare cases where i.e. Safari was ignoring the responsive children sizes</li>
		<li>Fixed drop zone issues in the overview and editor mode where dragging files from desktop over the browser was not always working well</li>
		<li>Fixed a bug where the slider timer was still processing after a slide change. Even pause on hover was activated</li>
		<li>Adding folders into other folders were not respecting the parent folder strucutre in the editor overview</li>
		<li>Fixed svg's at the layer import process to point to the correct path</li>
		<li>Fixed a preview slider bug where the order was not shown correctly</li>
		<li>Fixed a preview slider bug where unpublished slides would be shown</li>
		<li>Fixed a bug where custom animations where not transfered from v5 to v6. With this fix, missing v5 animations should now show up</li>
		<li>Fixed timeline option not working for some Facebook pages</li>
		<li>Fixed an issue where modal sliders did not show up when JavaScript was loading in footer</li>
		<li>Fixed iOS9 bugs</li>
		<li>Fixed double shown posters on YouTube background videos in Safari</li>
		<li>Fixed WhiteBoard ghost pixels in Firefox by removing the rotation effect of the "Hand" for Firefox. WhiteBoard 2.1 required</li>
		<li>Fixed an issue where 43+ layers exsits and the order of layers are equal to 6 + layer order. In this case it would fall back to the last order</li>
		<li>Typo issue fixed in file wp-content\plugins\revslider\admin\revslider-admin.class.php</li>
		<li>Fixed a bug where video or mp3 layers in the gobal layers would create an extra slide in the export file</li>
		<li>Fixed an issue where entering the viewport would restart layer videos even if this already paused/stopped due to another process</li>
		<li>Fixed looping issues in case the slider became hidden by exteral CSS/JavaScript code independet of the internal option hideSlideUnder</li>
		<li>Fixed an issue where invisible layers should be visible when hovering list elements in the editor</li>
		<li>Fixed a problem where auto played videos were not playing in carousel slider when all layers where shown at, once the option was selected and the slide change was processed</li>
		<li>Fixed audio layer issues in the global layers (visible control buttons, muted audio, etc.)</li>
		<li>Fixed videos that might be muted after import even if they should have sound on start</li>
		<li>Fixed the export/import of svg files not working properly</li>
		<li>Fixed exported zip files where they could not be imported again in certain circumstances</li>
		<li>Changes on the new custom navigation could not be saved before reloading the page. This issue has been fixed now</li>
		<li>Fixed placeholder feature for text and button layers to simplify the visible content on layers if needed</li>
		<li>Solved navigation styling issues in the editor</li>
		<li>Fixed loop effect animation issues with 0px dimensions</li>
		<li>Fixed carousel opacity, rotation, scale and vary opacity, vary rotation and vary scale options. You need to adjust the settings in some cases after this update!</li>
		<li>Fixed overview problems where modules were not showing up under folders in some very rare cases.</li>
		<li>Fixed an issue where adding bulk slides, importing slide(s) from templates or other modules did not save the slide content properly</li>
		<li>Importing layers modals will not open anymore if the import slide process started and the module has only one slide</li>
		<li>Fixed IE11 HTML5 bug</li>
		<li>Fixed IE11 navigation bugs</li>
		<li>Fixed migration issues where in the slide transition the first element was existing but was an empty string</li>
		<li>Fixed Instagram issue function 'instagram_autoloader' not found</li>
		<li>Fixed predefined height calculation of Sliders where preloaders on mobile devices were offset positioned</li>
		<li>Fixed import bug of static slides not deleting the old image id of a layer</li>
		<li>Fixed a scroll animation issue where a fullwidth slider position offsetted if the element was not embeded on a blank page template. Thanks to Kashif for the great suggestion!</li>
		<li>Updated missing media filters for the Pan Zoom effects</li>
		<li>Fixed "start with slide" in carousel mode which was somehow not fixed in version 6.1.2 due to a glitch</li>
		<li>Fixed issues in the overview/dashboard where some of the control buttons were not clickable in Safari Browser</li>
		<li>Fixed custom preset loading issues with the Particle Effects AddOn. Required version 2.1.0</li>
		<li>Fixed a notice that occured in a carousel if scale is set to off and fadeout is set to on</li>
		<li>Fixed issue where carousel elements scale over an acceptable limit. This value has been limited now</li>
		<li>Fixed line height issues on colums. Now you can also set line height defaults for columns to avoid spacing issues where layers within columns are lower than 25px</li>
		<li>Fixed a Paintbrush AddOn issue where the paintbrush option were not added to streams and post based sliders</li>
		<li>Fixed an issue with the carousel navigation due to bullets and arrows in some cases where the slide size was equal or bigger than screensize</li>
		<li>Fixed a markup issue in the overview where folder drop zones were not available anymore after last browser updates</li>
		<li>Fixed YouTube slide background images to show as default the high resolution image if available</li>
		<li>Fixed the tabs/thumbs navigation alignment navigation element styles with gaps issues.</li>
		<li>Fixed overall navigation align issues where rows and columns with media content added to stage</li>
		<li>Fixed covered background videos and covered layer videos in the Edge Browser</li>
		<li>Fixed styling issues of the pagination and sorting in the backend overview page</li>
		<li>Fullscreen video background sizes will calculate now already on the first load when the grid size is overdimensioned</li>
		<li>Fixed an issue where images with no dimension would break the editor at initialisation in Firefox</li>
		<li>Fixed Instagram fatal error in combination with older Essential Grid versions</li>
		<li>Fixed Instagram slide link {{link}} not working due to changed API structure</li>
		<li>Fixed Instagram connection issue for servers with 'allow_url_fopen' restriction</li>
		<li>Fixed Instagram stream {{link}} in slide link option not working</li>
		<li>Fixed many minor RTL styling issues in the editor</li>
		<li>Fixed IE11 issues. Now the slider works also with older Internet Explorer versions</li>
		<li>Fixed bad aligned layers when elements are center aligned with offsets. Requires the TypeWriter AddOn 2.0.1</li>
		<li>Installing template packages into folders will now respect the installation target folder also after reloading the page</li>
		<li>Fixed MS Edge masking issues, where layers were not correct rendering under mask animations</li>
		<li>Fixed blurry layers in Firefox that happened in some special cases</li>
		<li>Only real changes will be saved, independent what element has been touched during the session</li>
		<li>Fixed double starting of layers in carousel mode during auto processing of slides</li>
		<li>Fixed BubbleMorph on static layers. BubbleMorph version 2.0.2 is required</li>
		<li>Fixed the Nashville image filter with Ken Burns effect</li>
		<li>Fixed compatibility issues on older versions of iOS 9.x or newer</li>
		<li>Fixed "start with slide" value in carousel mode</li>
		<li>Fixed content jumping when a fullscreen slider is set up with min height values</li>
		<li>Fixed toggle mute/unmute of Vimeo videos on mobile issues</li>
		<li>Fixed layer video issue where "no loop" was not selectable together with the "auto progress of slide" option</li>
		<li>Removed folders will not break any more the last visited folder in the page editor</li>
        <li>Forced minify of icon fonts on frontend</li>
        <li>Fixed conflict with other extensions that have editor or admin in require config path</li>
        <li>Fixed error with preloaded Google fonts on frontend</li>
        <li>Fixed undefined punchgs error in sliders that use GS library in custom JavaScript</li>
        <li>Fixed Custom CSS/JS editor</li>
        <li>Fixed backend preview feature in minify and bundle js mode</li>
        <li>Fixed the slide sorting problem</li>
		<li>Fixed issue with image urls in multistore installation</li>
	</ul>

	<h3 class="version-number">Version 6.1.1.3 (25th May 2020)</h3>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
    <ul>
        <li>Changed Add-On download url</li>
    </ul>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Added missing minified font styles</li>
        <li>Added missing Store Visibility feature to slides</li>
    </ul>

	<h3 class="version-number">Version 6.1.1.2 (21th May 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed svg path error</li>
        <li>Fixed slider editor error in js bundle mode</li>
    </ul>

	<h3 class="version-number">Version 6.1.1.1 (20th May 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed get animations error</li>
    </ul>

	<h3 class="version-number">Version 6.1.1 (9th May 2020)</h3>
	<div class="newfeature"><strong style="font-weight:700">A New Content Building Standard.</strong></div>
	<ul>
		<li>The world's most powerful WordPress builder with advanced animations now on Magento 2</li>
		<li>Create outstanding, professional content modules with no coding experience required</li>
		<li>50+ new features</li>
		<li>Sliders & Carousels, Hero Headers, Content Blocks and Modules, Full Websites, Dynamic Solutions, Special FX</li>
		<li>Run any Slider Revolution module as a modal popup</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">The Visual Editor you want to work with.</strong></div>
	<ul>
		<li>Better usability</li>
		<li>Work faster & more efficiently</li>
		<li>Eye friendly dark user interface</li>
		<li>Improved loading times</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">The animators dream. Now with keyframes.</strong></div>
	<ul>
		<li>Easy to understand structure</li>
		<li>In-depth animation settings</li>
		<li>New easing types</li>
		<li>Animation presets</li>
		<li>Loop the whole timeline or between individual keyframes</li>
		<li>Scroll-based timeline animations</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">Mighty new content. Pure inspiration.</strong></div>
	<ul>
		<li>Many new templates</li>
		<li>New images, videos, icons, etc.</li>
		<li>Animated layer groups</li>
		<li>Quickstyle layer presets</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">Live help within the editor</strong></div>
	<ul>
		<li>Explanation for any option</li>
		<li>Search & highlight options</li>
		<li>Documentation & FAQ links</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">200+ ready to go templates</strong></div>
	<ul>
		<li>19 new templates added in 6.0</li>
		<li>The right template for every occasion</li>
		<li>From simple headers to full websites</li>
		<li>Special FX templates with add-ons</li>
	</ul>

</div>