<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\EnhancedEcommerce\Block\JsComponent **/
?>

<script type="text/x-magento-init">
    {
        "*": {
            "<?= /* @noEscape */ $block->getComponentName() ?>": {
                "dataLayerName": "<?= /* @noEscape */ $block->getDataLayerName() ?>",
                "currencyCode": "<?= /* @noEscape */ $block->getStoreCurrencyCode() ?>"
            }
        }
    }
</script>
