<?php
/* @var Tracking $block */

use Saee\ShipmentMethod\Block\Tracking;


?>
<style>
    .warning{
        background:#f89520;
        color: white;
    }
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        height:100px;
        overflow: auto;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
    .center {
        margin-left: auto;
        margin-right: auto;
    }
</style>
<h1><?php $items=$block->getData('details'); ?></h1>
<h1><?= $block->getText() ?></h1>
<form class="form" id="form" action="<?php echo $block->getBaseUrl().'tracking/index/index';?>" method="post">
    <div class="fieldset col-md-12">
        <div class="row">
        <div class="field required col-md-10">
            <label for="number" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Tracking Id') ?></span>
            </label>

            <div class="control">
                <input type="text" id="trackingnum"
                       name="trackingnum"
                       class="input-text" required>
            </div>
        </div>
        <div class="actions-toolbar col-md-2">
            <div class="primary">
                <button type="submit" class="action submit warning" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>
        </div>

    </div>
</form>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">

        </div>
    </div>
</div>

<?php if($block->getData('company_id')) {?>
    <table class="table-striped center">
        <thead>
        <tr>
            <th>Order Id</th>
            <th>Company Id</th>
            <th>City</th>
            <th>Notes</th>
            <th>Status</th>
         <th>Failed Attempts</th>
            <th>Reason Code</th>
            <th>Waybill</th>
        </tr>
        </thead>
        <?php foreach($items as $item){?>
                <tr>
                    <td><?= $block->getData('order_id')?></td>
                    <td><?= $block->getData('company_id')?></td>
                    <td><?=$item['city']?></td>
                    <td><?=$item['notes']?></td>
                    <td><?=$item['status']?></td>
                    <td><?=$block->getData('Failed_Delivery_Attempts')?></td>
                    <td><?=$block->getData('reason_code')?></td>
                    <td><?=$block->getData('waybill')?></td>

                </tr>
            <?php } ?>

    </table>
    <?php } else{?>
<h3 style="color:red"><?=$block->getData('error')?></h3>
<?php } ?>
<script>
    function testing() {
    }
</script>

