<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Affiliate for Magento 2
*/
?>
<div class="block block-collapsible-nav amasty-affiliate-collapsible">
    <div class="title block-collapsible-nav-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#amasty-affiliate-collapsible", "selectorsToggleClass": "active"}}'>
        <strong>Affiliate Account</strong>
    </div>
    <div class="content block-collapsible-nav-content" id="amasty-affiliate-collapsible">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
