<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use \Magento\Framework\App\Action\Action;

?>
<?php
$products = $this->getBestSellerProducts();
$helper = $this->helper('Evince\HomeProducts\Helper\Data');
$productRatingsHelper = $this->helper('Evince\ProductRatings\Helper\Data');
$viewAllHelper = $this->helper('Evince\ViewAll\Helper\Data');
$bestSellerViewAll = $viewAllHelper->getConfigValues('all/home/bestseller_url'); 
if(empty($bestSellerViewAll))
{
    $bestSellerViewAll = '#';
}
?>
<div class="best-seller-main block-title">
    <div class="best-seller-title title">
    	<div class="slider-heading"><h2><?php echo __('Best Sellers') ?></h2></div>
    	<div class="view-all-link">
            <a href="<?php echo $bestSellerViewAll ?>"><?= __('View All') ?></a>
        </div>	
    </div>
    <div id="owl-demo" class="owl-carousel owl-theme">

        <?php foreach ($products as $product): ?>

            <div class="item">
                <div class="product-item-info">
                    <a href="<?php echo $product->getProductUrl(); ?>" class="product-item-photo">
                        <img src="<?php echo $helper->getProductImageUrl($product); ?>" />
                    </a>
                    <div class="product-item-details">
                        <strong class="product-item-name">  
                            <a href="<?php echo $product->getProductUrl() ?>" class="product-item-link">
                                <?php echo $product->getName(); ?>
                            </a>
                        </strong>  
                        <div class="best-seller-ratings">
                            <?php /* product ratings start here */ ?>
                            <?php
                            $_ratingSummary = $productRatingsHelper->getRatingSummary($product);
                            $_reviewCount = ($product->getRatingSummary()->getReviewsCount() ? $product->getRatingSummary()->getReviewsCount() : '0')
                            ?>
                            <div class="product-reviews-summary short">
                                <div class="rating-summary">
                                    <div title="<?php echo (int) $_ratingSummary; ?>%" class="rating-result">
                                        <span style="width:<?php echo (int) $_ratingSummary; ?>%"><span><?php echo (int) $_ratingSummary; ?>%</span></span>
                                    </div>
                                </div>
                                <div class="reviews-actions">
                                    <?php echo __('' . $_reviewCount . ' Review(s)'); ?>
                                </div>
                            </div>
                            <?php /* product ratings end here */ ?>
                        </div>
                        <div class="best-seller-price">
                            <?php echo $this->getProductPriceHtml($product); ?>
                        </div>
                        <div class="product-item-inner">
                            <input type="hidden" class="popup-checkout-url" value="<?php echo $block->getUrl('checkout', ['_secure' => true]);?>" />
                            <div class="product actions product-item-actions">
                        <?php if ($product->isSaleable()) :?>
                            <?php $postParams = $block->getAddToCartParams($product); ?>
                            <form data-role="tocart-form"
                                  data-product-sku="<?= $block->escapeHtmlAttr($product->getSku()) ?>"
                                  action="<?= $block->escapeUrl($postParams['action']) ?>"
                                  method="post">
                                <input type="hidden"
                                       name="product"
                                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                <?= $block->getBlockHtml('formkey') ?>
                                <button type="submit"
                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                        class="action tocart primary">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                </button>
                            </form>
                        <?php else: ?>
                                <?php if ($product->isAvailable()) :?>
                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                <?php else :?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                <?php endif; ?>    
                        <?php endif; ?>
                        </div>
                    </div>
                    </div>
                </div>
            </div>

        <?php endforeach; ?>
    </div>
</div>
<div class="mobile_home_banner">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mobile_home')->toHtml(); ?>
</div>
<?php if(count($products)>0): ?>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($product->getSku()) ?>"
                }
            }
        }
</script>
<?php endif; ?> 
<script type="text/javascript" xml="space">// <![CDATA[
    //require(['jquery'], function () {
        require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {

            var isRTL = $("body").hasClass('rtl');
            $("#owl-demo").owlCarousel({
                /*margin:10,
                items:6,
                itemsDesktop: [1200, 6],
                itemsDesktopSmall: [992, 4],
                itemsTablet: [768, 3],
                itemsTabletSmall: [480, 2],
                itemsMobile: false,
                dots: false,
                navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                nav: true,
                loop: true*/
                margin:10,
                items: 6,
                //itemsDesktop: [1080, 6],
                //itemsDesktopSmall: [860, 3],
                //itemsTablet: [768, 3],
                //itemsTabletSmall: [639, 3],
                //itemsMobile: [479, 2],
                dots: false,
                rtl: isRTL,
                navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                nav: true,
                loop: true,
                responsive:{
                    0:{
                        items:2.5,
                        margin:0,
                    },
                    480:{
                        items:2.5,
                         margin:0,
                    },
                    768:{
                        items:2.5,
                         margin:2,
                    },
                    992:{
                        items:4,
                         margin:2,
                    },
                    1200:{
                        items:5
                    },
                    1300:{
                        items:6
                    }
                },
                /*responsive : {
                    // breakpoint from 0 up
                    0 : {
                       items:2
                    },
                    // breakpoint from 480 up
                    480 : {
                      items:3 
                    },
                    // breakpoint from 768 up
                    768 : {
                       item:4
                    },
                    1199 : {
                       item:6
                    }
                },*/
                
            });
        });
    //});
// ]]></script>

<style type="text/css">
    .owl-item {
  float: left;
}
.owl-carousel {
  overflow: hidden;
}
</style>
