<?php /** @var \Amasty\Reports\Block\Adminhtml\Report\Chart $block */ ?>
<?php
$axis = $block->getAxisFields();
$collection = $block->getCollection();
?>

<div class="amreports-amchart-wrapper" data-role="amreports-content">
    <?php if ($collection->getSize()) : ?>

        <?php foreach ($collection as $item) {
            $chartData[] = [
                "date" => $block->escapeHtml($item->getData($axis['y'])),
                "accounts" => $block->escapeHtml($item->getData('new_accounts')),
                "orders" => $block->escapeHtml($item->getData('orders')),
                "reviews" => $block->escapeHtml($item->getData('reviews'))
            ];
        } ?>

        <div id="chart-customers" class="amreports-amchart-container" data-chart-identifier="customers"></div>

        <script>
            require([
                "Amasty_Reports/vendor/amcharts4/core.min"
            ], function () {
                require([
                    "jquery",
                    "<?= /* @noEscape */ $block->getWidgetName('amreports_multi_linear_chart') ?>"
                ], function ($, widget) {
                    widget({
                        "data" : <?= /* @noEscape */ json_encode($chartData); ?>,
                        "selectorInit" : "chart-customers"
                    }, $('#chart-customers'));
                });
            });
        </script>

        <div class="listing">
            <?= $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
</div>
